### ISSUE TITLE
piksi_multi_cpp development

### ISSUE THREAD

**Issue by rikba** [ethz-asl/ethz_piksi_ros#102]
In https://github.com/ethz-asl/ethz_piksi_ros/pull/101 we introduced a first shot at a cpp ROS driver development. Several improvements and additions are necessary to make it usable.

- [x] Implement serial devices
- [x] Implement ethernet devices
- [x] Implement `readSettings` methods
- [x] Implement `writeSettings` methods
- [x] Identify Piksi Multi, e.g., base, reference receiver, attitude receiver
- [x] Expose all necessary SBP messages
- [x] Visualize certain messages
- [x] Multithreaded reading
- [ ] UML documentation
- [x] Launch files
- [x] Testing
- [x] ROS publisher architecture
- [x] Geo frame conversion
- [x] raw profiling
- [x] Group classes into folders
- [x] Improve sbp callback handler https://github.com/ethz-asl/ethz_piksi_ros/pull/103 https://github.com/ethz-asl/ethz_piksi_ros/pull/108
- [x] Create factory classes to avoid circular dependencies https://github.com/ethz-asl/ethz_piksi_ros/pull/107
- [x] Relay all sbp msgs
- [x] Send corrections by base station
- [x] Receive corrections by rover
- [x] Add callback to set current position as ENU reference
- [x] Base station sampling
- [ ] Consistent ros param reading

**Comment by michaelpantic** [comment]
I'll implement serial devices and publishing of corrections some time next week!

**Comment by rikba** [comment]
![IMG_20191009_111259412](https://user-images.githubusercontent.com/11293852/66551090-10e29180-eb47-11e9-90a3-c82ee659a0e3.jpg)

**Comment by michaelpantic** [comment]
Btw, that was the uml tool that @clanegge  used: http://plantuml.com/

**Comment by rikba** [comment]
Potential structure of SettingsIo/Receiver classes @michaelpantic 

![receiver_family](https://user-images.githubusercontent.com/11293852/67376359-4abe8980-f584-11e9-9318-28ee3582e4ce.png)
