### ISSUE TITLE
Does piksi_rtk_kml work with SPP/SBAS/RTK float?

### ISSUE THREAD

**Issue by ziliHarvey** [ethz-asl/ethz_piksi_ros#120]
Based on the instruction "The following launch file can be used to generate offline a KML file using a rosbag containing /piksi/navsatfix_rtk_fix topic", can it also be enabled for other topics like /piksi/navsatfix_rtk_float or /piksi/navsatfix_best_fix?
 Since I didn't always get consistent RTK Fixed signal.

**Comment by ziliHarvey** [comment]
Never mind. I wrote a tool for visualizing GPS trajectory that applies to all status in real time. Check it here if it's helpful:  https://github.com/ziliHarvey/GPS-Browser-Visualizer

**Comment by rikba** [comment]
Nice!
