### ISSUE TITLE
please retain compatibility with Kinetic

### ISSUE THREAD

**Issue by jbreiden2** [ethz-asl/ethz_piksi_ros#136]
Please consider changing this logging line to retain compatibility with Kinetic.

```diff
--- piksi_multi.py	2019-11-21 13:29:13.000000000 -0800
+++ piksi_multi.py	2019-11-22 11:00:38.000000000 -0800
@@ -1569,7 +1569,7 @@
         self.gyro_scale = gyro_range * PiksiMulti.kGyroPrescale
 
         self.has_imu_scale = True
-        rospy.loginfo_once("Received IMU scale.")
+        rospy.loginfo("Received IMU scale.")
 
     def cb_sbp_mag_raw(self, msg_raw, **metadata):
         msg = MsgMagRaw(msg_raw)
```

**Comment by rikba** [comment]
Please use [piksi_multi_cpp](https://github.com/ethz-asl/ethz_piksi_ros/tree/master/piksi_multi_cpp) with ROS noetic and Piksi Multi Firmware 2.4.16. The Python driver is not maintained and outdated. If you still want to use the Python driver checkout release [v1.10.0](https://github.com/ethz-asl/ethz_piksi_ros/tree/v1.11.0) or older versions.
