### ISSUE TITLE
/piksi/navsatfix_rtk_fix contains BASE coordinate 

### ISSUE THREAD

**Issue by zlg9folira** [ethz-asl/ethz_piksi_ros#148]
On a set of DURO receivers, I have configured base station and rover (as described [here](https://support.swiftnav.com/customer/portal/articles/2771177)). On rover side (using ethernet), I launch `piksi_multi_rover` as:

`roslaunch piksi_multi_rtk_ros piksi_multi_rover.launch`

followed by `rostopic echo /piksi/navsatfix_rtk_fix`. What I need is the coordinate of rover in RTKfix mode, however, the msgs of topic `/piksi/navsatfix_rtk_fix` contains the approximate coordinate of base station instead of rover. Is there any setting I missed ?

**Comment by rikba** [comment]
Please use [piksi_multi_cpp](https://github.com/ethz-asl/ethz_piksi_ros/tree/master/piksi_multi_cpp) with ROS noetic and Piksi Multi Firmware 2.4.16. The Python driver is not maintained and outdated. If you still want to use the Python driver checkout release [v1.10.0](https://github.com/ethz-asl/ethz_piksi_ros/tree/v1.11.0).

Make sure that the driver [connects to the correct device](https://github.com/ethz-asl/ethz_piksi_ros/blob/master/piksi_multi_cpp/launch/rover.launch#L3).
