### ISSUE TITLE
RTK gps in simulation

### ISSUE THREAD

**Issue by srsidd** [ethz-asl/ethz_piksi_ros#151]
Hello!
My question is related to the Piksi Multi, but may not be directly to this driver. We're trying model our robot in simulation and I wonder if there's a gazebo plugin for the Piksi multi and Duro?

I found a generic [GPS gazebo plugin](http://wiki.ros.org/hector_gazebo_plugins#GazeboRosGps), however it doesn't simulate the base-rover setup with the RTK fix. It also doesn't publish [odometry msgs](http://docs.ros.org/melodic/api/nav_msgs/html/msg/Odometry.html) and just publishes raw GPS data as a [NavsatFix msg](http://docs.ros.org/api/sensor_msgs/html/msg/NavSatFix.html). 

Do you have a recommendation on how this can be simulated in gazebo?

**Comment by rikba** [comment]
You could use our [geotf](https://github.com/ethz-asl/geodetic_utils/tree/master/geotf) package to convert navsatfix to ENU. Also we did start some GPS simulation on a branch [feature/gps_sim](https://github.com/ethz-asl/geodetic_utils/tree/feature/gps_sim) in that repository.
