### ISSUE TITLE
New Feature: Tool for visualizing gps trajectory and states display

### ISSUE THREAD

**Issue by ziliHarvey** [ethz-asl/ethz_piksi_ros#155]
Hi,
I've been using your ros package for a year and always didn't find a good way to visualize as Swift Console did. Hence, I wrote a browser-based GPS trajectory visualizer, which can subscribe to your topics and visualize in the map in real time, and will show different color w.r.t to current speed. I also made a panel to show fix mode, satellite number, etc. I think this could be a more convenient tool for visualization than converting to kml followed by displaying in google earth, and also more straightforward than just showing numbers from rqt_gps_rtk_plugin.
Can you please take a look? and **I'm wondering if my tool could be integrated into this repo**, since l believe this will benefit a lot for visualization purpose. Any opinion is welcomed, thanks!
https://github.com/ziliHarvey/GPS-Browser-Visualizer

**Comment by rikba** [comment]
Nice tool! I linked your project to the [README.md](https://github.com/ethz-asl/ethz_piksi_ros/blob/master/README.md#related-projects). But I don't think we will have it as part of this repo because we are rather looking to thin the repo out to make it easier to use.
