### ISSUE TITLE
Lib creation occurring before each node launch

### ISSUE THREAD

**Issue by dpiet** [ethz-asl/ethz_piksi_ros#165]
I'm running the v1.11.0 branch in ROS Melodic and we use catkin tools to manage our workspace. Each time we launch a piksi_multi_rtk_ros/piksi_multi node, it looks like it proceeds to recompile a required library even though nothing has changed and the library already exists from a previous node launch:

generating LLVM code for 'parse_jit_py27' into /tmp/pycc-build-parse_jit_py27-tcMFGr/parse_jit_py27.o
generating LLVM code for 'parse_jit_py27' into /tmp/pycc-build-parse_jit_py27-ZrCPQK/parse_jit_py27.o
C compiler: aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ByWuWM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC

creating /tmp/pycc-build-parse_jit_py27-tcMFGr/usr
creating /tmp/pycc-build-parse_jit_py27-tcMFGr/usr/local
creating /tmp/pycc-build-parse_jit_py27-tcMFGr/usr/local/lib
creating /tmp/pycc-build-parse_jit_py27-tcMFGr/usr/local/lib/python2.7
creating /tmp/pycc-build-parse_jit_py27-tcMFGr/usr/local/lib/python2.7/dist-packages
creating /tmp/pycc-build-parse_jit_py27-tcMFGr/usr/local/lib/python2.7/dist-packages/numba
creating /tmp/pycc-build-parse_jit_py27-tcMFGr/usr/local/lib/python2.7/dist-packages/numba/pycc
creating /tmp/pycc-build-parse_jit_py27-tcMFGr/usr/local/lib/python2.7/dist-packages/numba/cext
creating /tmp/pycc-build-parse_jit_py27-tcMFGr/usr/local/lib/python2.7/dist-packages/numba/runtime
compile options: '-DPYCC_MODULE_NAME=parse_jit_py27 -DPYCC_USE_NRT=1 -I/usr/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -c'
aarch64-linux-gnu-gcc: /usr/local/lib/python2.7/dist-packages/numba/cext/utils.c
C compiler: aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ByWuWM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC

creating /tmp/pycc-build-parse_jit_py27-ZrCPQK/usr
creating /tmp/pycc-build-parse_jit_py27-ZrCPQK/usr/local
creating /tmp/pycc-build-parse_jit_py27-ZrCPQK/usr/local/lib
creating /tmp/pycc-build-parse_jit_py27-ZrCPQK/usr/local/lib/python2.7
creating /tmp/pycc-build-parse_jit_py27-ZrCPQK/usr/local/lib/python2.7/dist-packages
creating /tmp/pycc-build-parse_jit_py27-ZrCPQK/usr/local/lib/python2.7/dist-packages/numba
creating /tmp/pycc-build-parse_jit_py27-ZrCPQK/usr/local/lib/python2.7/dist-packages/numba/pycc
creating /tmp/pycc-build-parse_jit_py27-ZrCPQK/usr/local/lib/python2.7/dist-packages/numba/cext
creating /tmp/pycc-build-parse_jit_py27-ZrCPQK/usr/local/lib/python2.7/dist-packages/numba/runtime
compile options: '-DPYCC_MODULE_NAME=parse_jit_py27 -DPYCC_USE_NRT=1 -I/usr/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -c'
aarch64-linux-gnu-gcc: /usr/local/lib/python2.7/dist-packages/numba/cext/dictobject.c
aarch64-linux-gnu-gcc: /usr/local/lib/python2.7/dist-packages/numba/pycc/modulemixin.c
aarch64-linux-gnu-gcc: /usr/local/lib/python2.7/dist-packages/numba/pycc/../runtime/nrt.c
aarch64-linux-gnu-gcc: /usr/local/lib/python2.7/dist-packages/numba/cext/listobject.c
aarch64-linux-gnu-gcc: /usr/local/lib/python2.7/dist-packages/numba/pycc/modulemixin.c
aarch64-linux-gnu-gcc: /usr/local/lib/python2.7/dist-packages/numba/pycc/../runtime/nrt.c
aarch64-linux-gnu-gcc: /usr/local/lib/python2.7/dist-packages/numba/pycc/../_math_c99.c
aarch64-linux-gnu-gcc: /usr/local/lib/python2.7/dist-packages/numba/cext/listobject.c
aarch64-linux-gnu-gcc: /usr/local/lib/python2.7/dist-packages/numba/cext/dictobject.c
aarch64-linux-gnu-gcc: /usr/local/lib/python2.7/dist-packages/numba/cext/utils.c
aarch64-linux-gnu-gcc: /usr/local/lib/python2.7/dist-packages/numba/pycc/../_math_c99.c
aarch64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ByWuWM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ByWuWM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security /tmp/pycc-build-parse_jit_py27-tcMFGr/parse_jit_py27.o /tmp/pycc-build-parse_jit_py27-tcMFGr/usr/local/lib/python2.7/dist-packages/numba/pycc/modulemixin.o /tmp/pycc-build-parse_jit_py27-tcMFGr/usr/local/lib/python2.7/dist-packages/numba/_math_c99.o /tmp/pycc-build-parse_jit_py27-tcMFGr/usr/local/lib/python2.7/dist-packages/numba/cext/utils.o /tmp/pycc-build-parse_jit_py27-tcMFGr/usr/local/lib/python2.7/dist-packages/numba/cext/listobject.o /tmp/pycc-build-parse_jit_py27-tcMFGr/usr/local/lib/python2.7/dist-packages/numba/cext/dictobject.o /tmp/pycc-build-parse_jit_py27-tcMFGr/usr/local/lib/python2.7/dist-packages/numba/runtime/nrt.o -L/usr/local/lib/python2.7/dist-packages/numpy/core/lib -lnpymath -lm -o /usr/local/lib/python2.7/dist-packages/sbp/jit/parse_jit_py27.so

This shared lib does exist in that python directory before node launch so I'm trying to understand where this is getting triggered and why. Thanks!

**Comment by rikba** [comment]
Please use [piksi_multi_cpp](https://github.com/ethz-asl/ethz_piksi_ros/tree/master/piksi_multi_cpp) with ROS noetic and Piksi Multi Firmware 2.4.16. The Python driver is not maintained and outdated.
