### ISSUE TITLE
ImportError: No module named zope.interface.exceptions

### ISSUE THREAD

**Issue by alan707** [ethz-asl/ethz_piksi_ros#166]
After launching the `piksi_multi_rover.launch` file, I get the following error:
```
ImportError: No module named zope.interface.exceptions
```

**Comment by rikba** [comment]
Please use [piksi_multi_cpp](https://github.com/ethz-asl/ethz_piksi_ros/tree/master/piksi_multi_cpp) with ROS noetic and Piksi Multi Firmware 2.4.16. The Python driver is not maintained and outdated. If you still want to use the Python driver checkout release [v1.10.0](https://github.com/ethz-asl/ethz_piksi_ros/tree/v1.11.0).
