### ISSUE TITLE
tf enu to base_link

### ISSUE THREAD

**Issue by pietrocolombo** [ethz-asl/ethz_piksi_ros#176]
Hi,
is it normal that there is no tf transformation between enu and base_link?
When I launch base_station and rover I have tf empty.

thank you

**Comment by rikba** [comment]
Hi

Yes, we do not publish a TF between enu and base_link. The reason is that we do not have orientation information from GNSS only. But we do publish the ENU `geometry_msgs::Point` as `/piksi/position_receiver_0/ros/pos_enu` to obtain some visualization.

**Comment by pietrocolombo** [comment]
thanks I hadn't thought of that
