### ISSUE TITLE
No data in every rostopic

### ISSUE THREAD

**Issue by jtang10** [ethz-asl/ethz_piksi_ros#178]
I cloned the version 1.11, fixed the bugs in piksi_multi_rtk_ros which prevent python3 working (mostly exception syntax change and byte to string issue), muted the unhandled bytes and turned on the debug mode. However, once I launched the rover node, no data at all came out of it. I have tried both simulation mode and real GPS signal and confirmed that there is data in the swift console.

**Comment by rikba** [comment]
Please use [piksi_multi_cpp](https://github.com/ethz-asl/ethz_piksi_ros/tree/master/piksi_multi_cpp) with ROS noetic and Piksi Multi Firmware 2.4.16. The Python driver is not maintained and outdated. If you still want to use the Python driver checkout release [v1.10.0](https://github.com/ethz-asl/ethz_piksi_ros/tree/v1.11.0).
