### ISSUE TITLE
"make -j28 -l28" failed

### ISSUE THREAD

**Issue by markewing93** [ethz-asl/ethz_piksi_ros#183]
When following the instructions at https://support.swiftnav.com/support/solutions/articles/44001907919-using-ros-with-swift-navigation-gnss-devices, I get the following errors when attempting the final catkin_make:
[ 11%] Built target rosserial_msgs_generate_messages_py
make[2]: *** No rule to make target 'ethz_piksi_ros/libsbp_ros_msgs/CMakeFiles/libsbp_ros_msgs.dir/build'.  Stop.
[ 11%] Built target rosserial_msgs_generate_messages_nodejs
CMakeFiles/Makefile2:3609: recipe for target 'ethz_piksi_ros/libsbp_ros_msgs/CMakeFiles/libsbp_ros_msgs.dir/all' failed
make[1]: *** [ethz_piksi_ros/libsbp_ros_msgs/CMakeFiles/libsbp_ros_msgs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 12%] Built target rosserial_msgs_generate_messages_eus
[ 13%] Built target rosserial_msgs_generate_messages_cpp
[ 14%] Built target rosserial_msgs_generate_messages_lisp
[ 29%] Built target piksi_rtk_msgs_generate_messages_nodejs
[ 42%] Built target piksi_rtk_msgs_generate_messages_lisp
[ 56%] Built target piksi_rtk_msgs_generate_messages_py
[ 70%] Built target piksi_rtk_msgs_generate_messages_eus
[ 84%] Built target piksi_rtk_msgs_generate_messages_cpp
[ 84%] Built target rosserial_arduino_generate_messages
[ 84%] Built target rosserial_mbed_generate_messages
[ 84%] Built target geotf
[ 85%] Built target set_gps_reference_node
[ 86%] Built target gps_to_pose_conversion_node
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j28 -l28" failed

I have spent the better part of a few hours going back and forth getting dependencies installed in a certain order that seemed to be neglected in the instructions, and for this to be the last thing in my way is highly frustrating. I never got any errors from libsbp when setting up piksi-rtk-messages, so I'm really at a loss for what is going on here. Any help is appreciated!

**Comment by rikba** [comment]
Please use [piksi_multi_cpp](https://github.com/ethz-asl/ethz_piksi_ros/tree/master/piksi_multi_cpp) with ROS noetic and Piksi Multi Firmware 2.4.16. The Python driver is not maintained and outdated. If you still want to use the Python driver checkout release [v1.10.0](https://github.com/ethz-asl/ethz_piksi_ros/tree/v1.11.0).
