### ISSUE TITLE
Wifi correction using rosmsg!!

### ISSUE THREAD

**Issue by JeyP4** [ethz-asl/ethz_piksi_ros#192]
Hello, I am trying for wifi correction.
Base station ip: 10.72.10.156, B. addr: 10.72.11.255       (University PC)
Rover ip          : 10.72.1.64    , B. addr: 10.72.1 .255        (Connected to university network through university VPN)

They can ping each other.
But as they have different B. addr, correction over wifi is not working.

Easy solution is connect VPN on base station also. {That adds another 10ms latency, thinking to avoid it}

Can you suggest something, if I try to do correction with help of a rosmsg instead of broadcasting over UDP?

**Comment by rikba** [comment]
If you can run ROS on the network you will probably also be able to send observations via WiFi. Try our new piksi_multi_cpp driver. This has different [configurations](https://github.com/ethz-asl/ethz_piksi_ros/blob/master/piksi_multi_cpp/launch/base.launch#L9-L16) how to send the corrections. 

If nothing works you may install a modem. Here are some instructions how to configure it. https://github.com/ethz-asl/ethz_piksi_ros/wiki/RFD-868x-Modem.

Please use [piksi_multi_cpp](https://github.com/ethz-asl/ethz_piksi_ros/tree/master/piksi_multi_cpp) with ROS noetic and Piksi Multi Firmware 2.4.16. The Python driver is not maintained and outdated. If you still want to use the Python driver checkout release [v1.10.0](https://github.com/ethz-asl/ethz_piksi_ros/tree/v1.11.0).
