### ISSUE TITLE
Heading information with two receivers on mobile robot

### ISSUE THREAD

**Issue by lipascal123** [ethz-asl/ethz_piksi_ros#199]
I have a mobile robot with two receivers and two antennas. I would like to get heading information as described here:  

https://support.swiftnav.com/support/solutions/articles/44001907898-rtk-heading-gnss-compass-configuration

Setup/Situation:
- Two Piksi Multis with firmware V2.3.19.
- I'm able to get rtk corrected positions.
- I use the correction data from swispos via the ntrip client.
- I connected both receivers to the onboard computer.
- When I check the swift console I can see the heading information computed by the attitude receiver (see attachment).

Problem:
- I'm not able to get the heading information published on a ros topic

Question:
- Is the ROS driver able to publish this heading information in my case onto a ros topic and if so which one?
- I'm only launching: piksi_multi_rtk_ros piksi_multi_rover.launch, is this correct?
- Is there anything I did not consider?
- I'm aware of the heading forwarding in firmware >v2.4... , I assume this is not yet integrated into the ros driver.

![Attitude_Receiver(1)](https://user-images.githubusercontent.com/43472532/120037056-4f211300-c001-11eb-80b6-bf4e7b259191.png)
![Reference_Receiver(1)](https://user-images.githubusercontent.com/43472532/120037058-4fb9a980-c001-11eb-9e18-65d0430736bf.png)

**Comment by rikba** [comment]
Hi @lipascal123 

if you can try to build and run our C++ ROS driver. https://github.com/ethz-asl/ethz_piksi_ros/blob/master/piksi_multi_cpp/launch/rover.launch

This will definitely forward the heading information. I'm not sure if we ever included it in the python version.
