### ISSUE TITLE
Documentation Images

### ISSUE THREAD

**Issue by marco-tranzatto** [ethz-asl/ethz_piksi_ros#2]

**Comment by marco-tranzatto** [comment]
![](https://cloud.githubusercontent.com/assets/5328930/24745681/c939fc5a-1ab6-11e7-803c-3ca9757c8375.png)

**Comment by marco-tranzatto** [comment]
![](https://cloud.githubusercontent.com/assets/5328930/24748214/4cdca622-1abf-11e7-9085-c2be2a5ebda2.png)

**Comment by marco-tranzatto** [comment]
![](https://cloud.githubusercontent.com/assets/5328930/24749637/1bc22df0-1ac4-11e7-8aa6-1b1671d6cea3.png)

**Comment by marco-tranzatto** [comment]
![](https://user-images.githubusercontent.com/5328930/29364649-81fdac56-8294-11e7-8753-931140b9cb3e.png)

**Comment by marco-tranzatto** [comment]
[xbibudev_referenceguide.pdf](https://github.com/ethz-asl/ethz_piksi_ros/files/1518439/xbibudev_referenceguide.pdf)

**Comment by marco-tranzatto** [comment]
![](https://user-images.githubusercontent.com/5328930/32789093-39c64746-c95b-11e7-9ad6-cf2d34132c2d.png)

**Comment by marco-tranzatto** [comment]
![](https://user-images.githubusercontent.com/5328930/32789100-3f764434-c95b-11e7-81a7-4b9af1f7bef5.png)

**Comment by marco-tranzatto** [comment]
![](https://user-images.githubusercontent.com/5328930/32789128-4bed2610-c95b-11e7-8347-72e74f127e5f.png)

**Comment by marco-tranzatto** [comment]
![](https://user-images.githubusercontent.com/15651057/33422109-c4559d8e-d5b4-11e7-91fc-ee0947c731d1.png)

**Comment by marco-tranzatto** [comment]
![](https://cloud.githubusercontent.com/assets/5328930/24755766/ad389370-1adb-11e7-8847-3ef72df36889.png)

**Comment by kholtmann** [comment]
![rtk_setup](https://user-images.githubusercontent.com/15651057/33481271-0b1b97ca-d694-11e7-8650-d3c7d2e54f7d.jpg)

**Comment by kholtmann** [comment]
GPS RTK setup - rover
![gps_rtk_setup_base_station](https://user-images.githubusercontent.com/15651057/36844735-2f50f534-1d54-11e8-904a-52762bc7dc28.png)

**Comment by kholtmann** [comment]
GPS RTK setup - rover
![gps_rtk_setup_rover](https://user-images.githubusercontent.com/15651057/36844765-49714748-1d54-11e8-86ed-5bb6b3fa747f.png)

**Comment by kholtmann** [comment]
Component images:
![gps_base_station_antenna_120](https://user-images.githubusercontent.com/15651057/36846815-6fb907a8-1d5c-11e8-882f-d8f827bf5318.png)
![gps_patch_antenna_120](https://user-images.githubusercontent.com/15651057/36846823-72def28a-1d5c-11e8-9e64-91227c074e1c.png)
![piksi_120](https://user-images.githubusercontent.com/15651057/36846827-767b498e-1d5c-11e8-8f74-fcf5efcc8777.png)
![sparkfun_120](https://user-images.githubusercontent.com/15651057/36846832-7a3b6af4-1d5c-11e8-9e25-f961797d8a29.png)
![upboard_120](https://user-images.githubusercontent.com/15651057/36846833-7c71e7ee-1d5c-11e8-967e-456d2e4ea4a1.png)
![xbee-xsc-rpsma_120](https://user-images.githubusercontent.com/15651057/36846837-802aba32-1d5c-11e8-8f29-5a45dbefba0a.png)
![pcb_120](https://user-images.githubusercontent.com/15651057/36846865-a869ea40-1d5c-11e8-99cd-f51ceddcf6fd.png)
![dipole_antenna_120](https://user-images.githubusercontent.com/15651057/36846891-c1bbb582-1d5c-11e8-8661-f582e0760537.png)

**Comment by marco-tranzatto** [comment]
[erl_beth_path.pdf](https://github.com/ethz-asl/ethz_piksi_ros/files/2103330/erl_beth_path.pdf)

**Comment by marco-tranzatto** [comment]
![kml_example](https://user-images.githubusercontent.com/5328930/41427607-c496cc26-7007-11e8-9ccb-2f6ec6b25ba6.png)
