### ISSUE TITLE
Error in ECEF to NED Conversion

### ISSUE THREAD

**Issue by specarmi** [ethz-asl/ethz_piksi_ros#205]
In the following lines:
https://github.com/ethz-asl/ethz_piksi_ros/blob/82a6f8123355e348f6cdb0f4dc0cc09e94e8e680/piksi_multi_rtk_ros/src/piksi_multi_rtk_ros/piksi_multi.py#L1265-L1266
it appears `phiP` is being set to the _geocentric_ latitude and is subsequently used to compute the rotation matrix from ECEF to NED (or North-East-Up in this case). The equations used to compute the rotation matrix assume _geodetic_ latitude, so `self.latitude0` should be used in place of `phiP`.

Also, `self.ecef_to_ned_matrix` rotates ECEF to North-East-Up instead of North-East-Down. This is accounted for in `ecef_to_ned`:
https://github.com/ethz-asl/ethz_piksi_ros/blob/82a6f8123355e348f6cdb0f4dc0cc09e94e8e680/piksi_multi_rtk_ros/src/piksi_multi_rtk_ros/piksi_multi.py#L1295
but it seems like it would be more straightforward to flip the sign on these lines:
https://github.com/ethz-asl/ethz_piksi_ros/blob/82a6f8123355e348f6cdb0f4dc0cc09e94e8e680/piksi_multi_rtk_ros/src/piksi_multi_rtk_ros/piksi_multi.py#L1320-L1322

**Comment by rikba** [comment]
Please use [piksi_multi_cpp](https://github.com/ethz-asl/ethz_piksi_ros/tree/master/piksi_multi_cpp) with ROS noetic and Piksi Multi Firmware 2.4.16. The Python driver is not maintained and outdated. If you still want to use the Python driver checkout release [v1.10.0](https://github.com/ethz-asl/ethz_piksi_ros/tree/v1.11.0).

The piksi_multi_cpp uses gdal to convert between frames and should thus be relatively safe with respect to frame conversions.
