### ISSUE TITLE
Driver Installation Error (llvmlite) and Standalone GNSS mode

### ISSUE THREAD

**Issue by hizamkamis** [ethz-asl/ethz_piksi_ros#206]
**Fixed the llvmlite error by running sudo pip3 install llvmlite --upgrade in install_piksi_multi.sh file**

Hi,

I encountered an error when the ./install_piksi_multi.sh script is trying to install llvmlite. I am running Ubuntu 18.04, ROS Melodic.
 
**#### Run the install script**
./install_piksi_multi.sh
Page Reference: https://support.swiftnav.com/support/solutions/articles/44001907919-using-ros-with-swift-navigation-gnss-devices

Separately, am wondering whether this driver also supports **Standalone Position** mode (not just **RTK** mode)?

**Comment by rikba** [comment]
Please use [piksi_multi_cpp](https://github.com/ethz-asl/ethz_piksi_ros/tree/master/piksi_multi_cpp) with ROS noetic and Piksi Multi Firmware 2.4.16. The Python driver is not maintained and outdated. If you still want to use the Python driver checkout release [v1.10.0](https://github.com/ethz-asl/ethz_piksi_ros/tree/v1.11.0).

And yes, especially the piksi_multi_cpp driver will relay every GNSS measurement of the swift piksi. Even raw pseudoranges.
