### ISSUE TITLE
Catkin_make problem

### ISSUE THREAD

**Issue by MKMTI** [ethz-asl/ethz_piksi_ros#210]
Hello,
I am doing a project using an GNSS of SwiftNavigation and to do so I need this package. I did every step that Swift Navigation tells to do, however, when I do:

"catkin_make --pkg piksi_rtk_msgs" there is an error cause he doesn't find the src/conversion.cc, so I commented it in the CMakeLists.txt and it worked.

However whenever I try to do "catkin_make" it appears an error saying : 
"[  1%] Completed 'libsbp'
[  2%] Built target libsbp
make: *** [Makefile:141: all] Erro 2
Invoking "make install -j8 -l8" failed"

Now I am at a corner not to know what to do. Can anyone help me?

Thanks,
Tiago

**Comment by rikba** [comment]
Please use [piksi_multi_cpp](https://github.com/ethz-asl/ethz_piksi_ros/tree/master/piksi_multi_cpp) with ROS noetic and Piksi Multi Firmware 2.4.16. The Python driver is not maintained and outdated. If you still want to use the Python driver checkout release [v1.10.0](https://github.com/ethz-asl/ethz_piksi_ros/tree/v1.11.0).
