### ISSUE TITLE
Installation piksi_multi_cpp

### ISSUE THREAD

**Issue by JonasFrey96** [ethz-asl/ethz_piksi_ros#221]
Could you add in the README to install:
```
sudo apt-get install -y libserialport-dev
```
and
```
pip3 install voluptuous 
pip3 install Jinja2
```

**Comment by rikba** [comment]
This should be part of `./ethz_piksi_ros/piksi_multi_cpp/install/prepare-jenkins-slave.sh` step.

https://github.com/ethz-asl/ethz_piksi_ros/pull/211/files
