### ISSUE TITLE
Using piksi_multi_rtk_ros with robot_localization

### ISSUE THREAD

**Issue by KorvoSohlstrom** [ethz-asl/ethz_piksi_ros#223]
I am trying to get robot localization working on melodic using `piksi_multi_rtk_ros` with the `robot_localization` node. The 'piksi_multi_rtk_ros' provides `NavSatFix` and `Imu` topics but not odometry. In what ways could I feed the piksi into `robot_localization`?

**Comment by rikba** [comment]
Sorry, I'm not familiar with robot_localization but I think you can somehow feed it navsatfix or maybe also pos_enu (geometry_msgs/Point) messages.

**Comment by pietrocolombo** [comment]
If you do not have `odometry`, you can produce it with `robot_localisation` using `NavSatFix` and `Imu`.
Obviously it would be better to have it from encoder data.
