### ISSUE TITLE
Compatibility with FW: 1.5.12

### ISSUE THREAD

**Issue by Locky083** [ethz-asl/ethz_piksi_ros#32]
I updated my Duro to the latest 1.5.12 Firmware.  All GPS related data no longer broadcaster to topics, even gps_time.   ImuRaw still seems to be functional

**Comment by marco-tranzatto** [comment]
Hi, this ROS driver has not been updated yet to match the latest firmware (which was released yesterday).
This section [Firmware and SBP Lib version](https://github.com/ethz-asl/ethz_piksi_ros/tree/master/piksi_multi_rtk_ros#firmware-and-sbp-lib-version) reports which Firmware and SBP library are currentely used by the driver.

Regards,
Marco.
