### ISSUE TITLE
Magnetometer implementation

### ISSUE THREAD

**Issue by Wagdi-Benyaala** [ethz-asl/ethz_piksi_ros#34]
Hi,

I just implemented the callback and publisher for the magnetometer.

Are you opened for Pull requests ?

Best,

**Comment by marco-tranzatto** [comment]
Hi,

yes, we welcome PRs that respect the code style. Also there was somebody else interested in this topic: #31

**Comment by Wagdi-Benyaala** [comment]
Hi,

I just did the PR. I will be waiting for your approval.

Best,

**Comment by marco-tranzatto** [comment]
Merged with PR #35
