### ISSUE TITLE
Convert IMU_RAW to ros message

### ISSUE THREAD

**Issue by mdemirst** [ethz-asl/ethz_piksi_ros#44]
Swift publishes raw imu and magnetometer messages. Can you convert them to ros imu message?

**Comment by marco-tranzatto** [comment]
Hi, we decided to publish raw messages as are given by Piksi Multi, especially because there's a scaling factor you should consider when converting raw measurements to SI units for standard ROS message. You can covert them in standard ROS message using a custom python script for instance.
