### ISSUE TITLE
Launch file default value overwrites yaml cfg file

### ISSUE THREAD

**Issue by pedro1713** [ethz-asl/ethz_piksi_ros#48]
I changed the baud_rate parameter in the yaml file to the Piksi default of 115200. As of the latest version the newly added default in piksi_multi_rover.launch overwrites my change in the yaml file.

**Comment by kholtmann** [comment]
Hi @pedro1713 
This is correct; the parameters provided via launch file overwrite the ones specified in the [config file](https://github.com/ethz-asl/ethz_piksi_ros/blob/master/piksi_multi_rtk_ros/cfg/piksi_multi_driver_settings.yaml) and therefore, also the [baud_rate](https://github.com/ethz-asl/ethz_piksi_ros/blob/d3a92c92c8b301e61b4a827f32d6fbfc94619743/piksi_multi_rtk_ros/launch/piksi_multi_rover.launch#L8) parameter.

If you want to change the `baud_rate` to be 115200 you can either:
  1. change the value of the `baud_rate` parameter in the launch file, or
  2. remove the `baud_rate` parameter from the launch file, such that only the one in the config file is loaded.
