### ISSUE TITLE
Update for firmware v2.0

### ISSUE THREAD

**Issue by matteopantano** [ethz-asl/ethz_piksi_ros#56]
Will be there an update to the repository for firmware v2.0 of piksi multi?

**Comment by kholtmann** [comment]
Eventually there might be. We did not have time to work on it yet.

**Comment by matteopantano** [comment]
Ok, thanks

**Comment by matteopantano** [comment]
Hey @rikba I am using the Feature/v2.1.14. I had forked the repo and I have had several issues with the installation, however the major one was that the install script does not remove the old libsbp located in `/usr/local/lib/python2.7/dist-packages/sbp-*`. Did you encounter the same problem?

**Comment by rikba** [comment]
Hi @matteopantano, 

I don't remember having issues running the install script. But I think I installed on a clean machine. 

Were you finally able to install and test the new version?

**Comment by matteopantano** [comment]
Yes I have manually deleted old libsbp and now I am using the driver. If you want I can open a fork so you can evaluate the modifications that I did

**Comment by kinergy** [comment]
don't think we had an issue with this - we switched to branch Feature/v2.1.14 and used the install script as is. I see that `sbp-2.4.1-py2.7.egg` is the only sbp- present.

**Comment by marco-tranzatto** [comment]
Firmware updated to 2.1.14 after PR #63
