### ISSUE TITLE
Using driver with two receivers on rover, baseline heading

### ISSUE THREAD

**Issue by apalomino-edgebrain** [ethz-asl/ethz_piksi_ros#64]
I have a set up of a base station and two receivers on the rover to enable heading output using the following [configuration]( https://support.swiftnav.com/customer/portal/articles/2805901-piksi-multi---heading). The corrections are sent from base station to reference receiver by radio link and from reference to attitude receiver by serial, so not using the ROS driver for now. But we're rather interested in getting the published topics of both receivers on the rover for position and heading solutions. 
Now I'm just launching two instances of `piksi_multi_rtk_ros piksi_multi_rover.launch`, one for each receiver with different `tcp_addr`. 

Could you give me advice on how to get the `/baseline_heading` properly if supported by the current version of the driver? 

Besides, we're looking for a robust industrial implementation specially interested in the improvements of Firmware v2.1.14. Do you know what is the current state of this feature [#63](https://github.com/ethz-asl/ethz_piksi_ros/pull/63) in terms of RTK position and heading solution? We might start testing and help to get the release soon.

**Comment by rikba** [comment]
Hi @apalomino-edgebrain 

We just tried this configuration in https://github.com/ethz-asl/ethz_piksi_ros/pull/92.

In our launch file we start two ROS drivers, one for each receiver with different `tcp_addr` as you did.
```
      <!-- Piksi reference receiver -->
      <node pkg="piksi_multi_rtk_ros" type="piksi_multi" name="piksi_ref" output="screen">
        <rosparam command="load" file="$(find fm_missions)/cfg/piksi/piksi_ref.yaml" />
      </node>

      <!-- Piksi attitude receiver -->
      <node pkg="piksi_multi_rtk_ros" type="piksi_multi" name="piksi_att" output="screen">
        <rosparam command="load" file="$(find fm_missions)/cfg/piksi/piksi_att.yaml" />
      </node>
```

Make sure that the heading message is published by the piksi board, i.e., [message 527](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=2ahUKEwi9hYqO0tXkAhUPqIsKHXDzBNcQFjABegQIABAC&url=https%3A%2F%2Fwww.swiftnav.com%2Flatest%2Fsbp-specification&usg=AOvVaw07PYsRq36BKhJh_klE3LmH) is published when you configure the ethernet interface in swift console. 

I'll try to upload an example attitude receiver configuration with the open PR.
