### ISSUE TITLE
Connection to other Radio Modules

### ISSUE THREAD

**Issue by matteopantano** [ethz-asl/ethz_piksi_ros#7]
Hi,

I would like to connect the Piksi Multi with the FreeWave radio [module](http://www.freewave.com/products/mm2-series/) provided by Swiftnav. Is this compliant with the package? Can I still use the feature of double communication between Wi-Fi and radio module? Or do you suggest to use the Xbee? 
Thanks.

Matteo

**Comment by marco-tranzatto** [comment]
Hi Matteo,

Our ROS driver does not rely on any radio link communication but they add a WiFi link to send correction, so yes, you can use any radio that is compatible with Piksi Multi. You'll need to adjust some settings accordingly (for example `uart0.baudrate`) to the radio module you want to use.

Marco.
