### ISSUE TITLE
Create new Settings for Firmware 2.1.14

### ISSUE THREAD

**Issue by marco-tranzatto** [ethz-asl/ethz_piksi_ros#74]
After PR #63 is merged, new settings for `Rover Piksi Multi - Firmware v2.1.14 (21/02/2019)` in [rover-hardware--firmware](https://github.com/ethz-asl/ethz_piksi_ros/wiki/Installing-and-Configuring-Your-Piksi-Multi#rover-hardware--firmware) and in `Base Station Piksi Multi - Firmware v2.1.14 (21/02/2019)` in [base-station-hardware--firmware](https://github.com/ethz-asl/ethz_piksi_ros/wiki/Installing-and-Configuring-Your-Piksi-Multi#base-station-hardware--firmware) should be generated. I can explain you how to do it in person.

**Comment by rikba** [comment]
Skipped this version but created settings for v2.1.19.
