### ISSUE TITLE
Readme Advertised topics page not found

### ISSUE THREAD

**Issue by ziliHarvey** [ethz-asl/ethz_piksi_ros#78]
Hi,
In /ethz_piksi_ros/piksi_multi_rtk_ros/README.md, when clicked the link in "For a complete list of advertised topics please check function advertise_topics.", it shows 404 not found.
Can you please update the advertised topics link?

**Comment by marco-tranzatto** [comment]
Hi,

advertised topics can be found here: [https://github.com/ethz-asl/ethz_piksi_ros/blob/master/piksi_multi_rtk_ros/src/piksi_multi_rtk_ros/piksi_multi.py#L196](https://github.com/ethz-asl/ethz_piksi_ros/blob/master/piksi_multi_rtk_ros/src/piksi_multi_rtk_ros/piksi_multi.py#L196)

Regards,
Marco.
