### ISSUE TITLE
'kAccPrescale' is not defined

### ISSUE THREAD

**Issue by Roboterbastler** [ethz-asl/ethz_piksi_ros#81]
Hi,

I'm using Piksi Multi (hardware v2.2.17) and am trying to launch the `piksi_multi_rtk_ros piksi_multi_rover.launch`. I'm using Ubuntu 18.04.2 and ROS Melodic.

I had multiple problems installing the SBP library. According to my hardware version I set `REPO_TAG=v2.4.7` in the install script. First problem that came up was basically the same as in https://github.com/kalliope-project/kalliope/issues/487 and appeared when I ran the install script, so I applied the same "fix":

```
sudo chmod -R o+r /usr/local/lib/python2.7/dist-packages/
```

Secondly I had to manually append the path to `$PYTHONPATH` in order that the SBP library was found:

```
export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/dist-packages/
```

Now the node seems to start but crashes with the following error:

```
process[piksi-2]: started with pid [18760]
[INFO] [1559310610.854668][/piksi][[..]/ethz_piksi_ros/piksi_multi_rtk_ros/src/piksi_multi_rtk_ros/piksi_multi.py:81]: /piksi start
[INFO] [1559310611.404599][/piksi][[..]/ethz_piksi_ros/piksi_multi_rtk_ros/src/piksi_multi_rtk_ros/piksi_multi.py:89]: libsbp version currently used: 2.4.7
[WARN] [1559310611.405649][/piksi][[..]/ethz_piksi_ros/piksi_multi_rtk_ros/src/piksi_multi_rtk_ros/piksi_multi.py:95]: Lib SBP version in usage (2.4.7) is different than the one used to test this driver (2.4.1)!
Please run the install script: 'install/install_piksi_multi.sh'
('192.168.3.34', 55556)
[INFO] [1559310611.497396][/piksi][[..]/ethz_piksi_ros/piksi_multi_rtk_ros/src/piksi_multi_rtk_ros/piksi_multi.py:130]: Swift driver started in normal mode.
Traceback (most recent call last):
  File "[..]/ethz_piksi_ros/piksi_multi_rtk_ros/bin/piksi_multi", line 6, in <module>
    piksi_multi = PiksiMulti()
  File "[..]/ethz_piksi_ros/piksi_multi_rtk_ros/src/piksi_multi_rtk_ros/piksi_multi.py", line 178, in __init__
    self.acc_scale = 8 * kAccPrescale
NameError: global name 'kAccPrescale' is not defined
[piksi-2] process has died [pid 18760, exit code 1, cmd [..]/ethz_piksi_ros/piksi_multi_rtk_ros/bin/piksi_multi __name:=piksi __log:=[..]
```

According to the wiki `ethz_piksi_ros` has only been tested with Ubuntu 16.04 and ROS Kinetic, does someone have an idea what could be going wrong in my case? Did anyone successfully run it with 18.04/Melodic?

**Comment by marco-tranzatto** [comment]
Fixed in PR #82
