### ISSUE TITLE
yaml parser install failure

### ISSUE THREAD

**Issue by khlitoshi** [ethz-asl/ethz_piksi_ros#87]
Hi,
I believe you need to add a command to automatically upgrade "setuptools" so that yaml parser is installed without issue.
`sudo pip install -U setuptools`

**Comment by rikba** [comment]
We have [simplified the installation](FYI we massively simplified the [installation script](https://github.com/ethz-asl/ethz_piksi_ros/blob/v1.11.0/piksi_multi_rtk_ros/install/install_piksi_multi.sh) in the newest version. You may want to have another try.) in the newest version. Hopefully this fixes the missing dependency.
