### ISSUE TITLE
Ethernet Connection

### ISSUE THREAD

**Issue by JadTawil-theonly** [ethz-asl/ethz_piksi_ros#91]
How can i connect to my piksi multis with ethernet?

**Comment by rikba** [comment]
The [evaluation board](https://support.swiftnav.com/customer/en/portal/articles/2681333-piksi-multi-evaluation-board) exposes the ethernet port. When starting the ROS driver you need to set the [interface](https://github.com/ethz-asl/ethz_piksi_ros/blob/master/piksi_multi_rtk_ros/launch/piksi_multi_rover.launch#L6) to 'tcp' and fix the [tcp_address](https://github.com/ethz-asl/ethz_piksi_ros/blob/master/piksi_multi_rtk_ros/launch/piksi_multi_rover.launch#L10) (default '192.168.0.222').
