### ISSUE TITLE
Duro inertial bug when INS enabled

### ISSUE THREAD

**Issue by ihsane-d** [ethz-asl/ethz_piksi_ros#96]
Hi, I am having issues running Piksi_Multi_RTK_ROS with the Duro Inertial.
I installed libsbp v2.6.3 which corresponds to firmware version 2.3.17. When INS mode is set to loosely coupled I get this error message upon running the ROS node (no topic data is published):

[ERROR] [1569019524.094345]: [cb_sbp_pos_llh]: Unknown case, you found a bug!Contact the package/repository maintainers.Report: 'msg.flags = 14'
[ERROR] [1569019524.164655]: [cb_sbp_pos_llh]: Unknown case, you found a bug!Contact the package/repository maintainers.Report: 'msg.flags = 14'
[ERROR] [1569019524.279918]: [cb_sbp_pos_llh]: Unknown case, you found a bug!Contact the package/repository maintainers.Report: 'msg.flags = 14'

Everything runs fine when INS output mode is set to disabled

**Comment by chriswsuarez** [comment]
Was this issue completely resolved?  I'm seeing this error in the exact same situation.

[ERROR] [1589569927.991585]: [cb_sbp_pos_llh]: Unknown case, you found a bug!Contact the package/repository maintainers.Report: 'msg.flags = 8'
[ERROR] [1589569928.089056]: [cb_sbp_pos_llh]: Unknown case, you found a bug!Contact the package/repository maintainers.Report: 'msg.flags = 8'
[ERROR] [1589569928.187506]: [cb_sbp_pos_llh]: Unknown case, you found a bug!Contact the package/repository maintainers.Report: 'msg.flags = 8'
