### ISSUE TITLE
Heading/Track information

### ISSUE THREAD

**Issue by zlg9folira** [ethz-asl/ethz_piksi_ros#99]
Does the driver publish heading/track information with respect to north of globe ? If it doesn't, what are the workarounds to get that with Piksi Multi?

**Comment by rikba** [comment]
Yes you can get the heading with Piksi Multi, see also https://github.com/ethz-asl/ethz_piksi_ros/issues/64 .
You need a [moving baseline setup](https://support.swiftnav.com/customer/en/portal/articles/2805901-piksi-multi---heading) with two antennas and Piksis though.
